# NumPy Commands

1. min
2. max
2. mean
3. argmin
4. argmax
5. linalg.solve
6. flatten
7. ravel
8. dot Product
9. \* for Matrix (Element wise multiplication)
10. arange followed by reshape
11. identity / eye
12. sum
13. diag
14. tril / triu

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
z = np.zeros((2,3))
z.shape

(2, 3)

In [4]:
mat = np.full((2,5),-1)
mat

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [35]:
ran = np.random.random((3,4))
ran

array([[ 0.32379286,  0.9868565 ,  0.33489642,  0.17254004],
       [ 0.54939084,  0.9767883 ,  0.395017  ,  0.98816258],
       [ 0.91706306,  0.3197481 ,  0.66492231,  0.97682321]])

## Min

In [36]:
ran.min()

0.17254004141681767

In [37]:
ran.min(axis=0)

array([ 0.32379286,  0.3197481 ,  0.33489642,  0.17254004])

## Max

In [38]:
ran.max(axis=1)

array([ 0.9868565 ,  0.98816258,  0.97682321])

## Mean

In [39]:
ran.mean()

0.63383343379062917

## Argmin

In [40]:
ran.argmin(axis=1)

array([3, 2, 1])

## Argmax

In [41]:
ran.argmax()

7

## Linalg.solve

In [42]:
a = np.array([[4,3],[5,2]])
b = np.array([3,8])
x = np.linalg.solve(a,b)
x

array([ 2.57142857, -2.42857143])

## Flatten

In [53]:
ran.flatten(order='C')

array([ 0.32379286,  0.9868565 ,  0.33489642,  0.17254004,  0.54939084,
        0.9767883 ,  0.395017  ,  0.98816258,  0.91706306,  0.3197481 ,
        0.66492231,  0.97682321])

## Ravel

In [50]:
ran.ravel()

array([ 0.32379286,  0.9868565 ,  0.33489642,  0.17254004,  0.54939084,
        0.9767883 ,  0.395017  ,  0.98816258,  0.91706306,  0.3197481 ,
        0.66492231,  0.97682321])

## Dot

In [64]:
b = np.full((3,3),-5)
a=np.random.random((3,3))
np.dot(a,b)

array([[-8.44765096, -8.44765096, -8.44765096],
       [-9.88879267, -9.88879267, -9.88879267],
       [-5.74351468, -5.74351468, -5.74351468]])

## Element Wise Multiplication

In [70]:
np.multiply(b,i)

array([[-5., -0., -0.],
       [-0., -5., -0.],
       [-0., -0., -5.]])

## Arrange and Reshape

In [83]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Eye

In [67]:
i = np.eye(3)
i

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Sum

In [85]:
ran.sum(axis=0)

array([ 1.79024676,  2.28339289,  1.39483573,  2.13752583])

## Diag

In [91]:
np.diag(ran)

array([ 0.32379286,  0.9767883 ,  0.66492231])

## Tril/Triu

In [98]:
np.tril(ran,1)

array([[ 0.32379286,  0.9868565 ,  0.        ,  0.        ],
       [ 0.54939084,  0.9767883 ,  0.395017  ,  0.        ],
       [ 0.91706306,  0.3197481 ,  0.66492231,  0.97682321]])

In [99]:
np.triu(ran,-1)

array([[ 0.32379286,  0.9868565 ,  0.33489642,  0.17254004],
       [ 0.54939084,  0.9767883 ,  0.395017  ,  0.98816258],
       [ 0.        ,  0.3197481 ,  0.66492231,  0.97682321]])