# What is CNN ?


#### A CNN is a neural network that typically contains several types of layers, which includes :-

* convolutional layer 
* pooling layer, and 
* activation layer.

## Convolutional Layer

* To understand what a CNN is, you need to understand how convolutions work. 

* Imagine you have an image represented as a 5x5 matrix of values, and you take a 3x3 matrix and slide that 3x3 window around the image. 

* At each position the 3x3 visits, you matrix multiply the values of your 3x3 window by the values in the image that are currently being covered by the window. 

* This results in a single number the represents all the values in that window of the image. 

Here’s a gif for clarity:

![Conv Gif](./conv.gif)

## Level - 1 - Code the Convolutional Layer


![Detailed Conv Gif](./conv_detailed.gif)

### Question 1

In [1]:
# Write a function which does the convolution.
# Code for a 3d Matrix
# Before writing out code, write function header with parameters and get it reviewed by Mentors

import pandas as pd
import numpy as np

In [7]:
#sliding window
def find_mat(img,kernel,r=0,c=0):
    r_kernel, c_kernel = kernel.shape[0], kernel.shape[1]
    temp_img = np.zeros((r_kernel,c_kernel))
    v = 0
    for i in range(r,r+r_kernel):
        u = 0
        for j in range(c,c+c_kernel):
            temp_img[v,u]=img[i,j]
            u = u+1
        v = v +1   
    return temp_img    

In [2]:
#conv function
def conv_mult(stride):
    global img, kernel
    r_img, c_img = img.shape[0], img.shape[1]
    r_kernel, c_kernel = kernel.shape[0], kernel.shape[1]
    r_range, c_range = int(np.ceil((r_img - r_kernel)/stride) + 1), int(np.ceil((c_img - c_kernel)/stride) + 1)
    r_list = []
    r_list.extend(range(0,r_img))
    r_list = r_list[::stride][0:r_range]
    c_list = []
    c_list.extend(range(0,c_img))
    c_list = c_list[::stride][0:c_range]
    k=0
    ans=np.zeros((r_range,c_range))
    for r in r_list:
        h=0
        for c in c_list:
            test1 = find_mat(img,kernel,r,c)
            a = np.multiply(test1,kernel)
            temp = sum(sum(a))
            ans[k,h]=temp
            h+=1
        k+=1
    return ans

In [4]:
#check conv
img = np.random.random((6,6))
kernel = np.random.random((3,3))
stride = int(input("enter the stride : "))
x = conv_mult(stride)
print("convolution output:\n",x)

enter the stride : 1
convolution output:
 [[ 1.61361828  2.16005909  2.66923012  2.51435815]
 [ 2.57160392  3.02018296  2.55107891  1.47491089]
 [ 2.44073426  2.73076397  2.2460237   1.31543706]
 [ 2.07084908  2.2090946   2.1530627   2.05220764]]


## Pooling Layers

* Pooling works very much like convoluting, where we take a kernel and move the kernel over the image, the only difference is the function that is applied to the kernel and the image window isn’t linear.

* Max pooling and Average pooling are the most common pooling functions. 

* Max pooling takes the largest value from the window of the image currently covered by the kernel, while average pooling takes the average of all values in the window.

![Pooling Gif](./pooling.gif)

## Level - 2 - Code the Pooling Layer

![Detailed Conv Gif](./Max_pooling.png)

### Question 1

In [ ]:
# Write a function which does the max pooling.
# Code for a 3d Matrix
# Before writing out code, write function header with parameters and get it reviewed by Mentors

def max_pool(img, kernel):
    r_img, c_img = img.shape[0], img.shape[1]
    r_kernel, c_kernel = kernel.shape[0], kernel.shape[1]
    stride = r_kernel
    r_range, c_range = int(np.ceil((r_img - r_kernel)/stride) + 1), int(np.ceil((c_img - c_kernel)/stride) + 1)
    r_list = []
    r_list.extend(range(0,r_img))
    r_list = r_list[::stride][0:r_range]
    c_list = []
    c_list.extend(range(0,c_img))
    c_list = c_list[::stride][0:c_range]
    k=0
    ans=np.zeros((r_range,c_range))
    for r in r_list:
        h=0
        for c in c_list:
            test1 = find_mat(img,kernel,r,c)
            m = test1.max()
            ans[k,h]=m
            h+=1
        k+=1
    return ans

In [8]:
#check max pooling function
pool_filter = np.random.random((2,2))
max_mat = max_pool(x,pool_filter)
print("max matrix :\n",max_mat)

max matrix :
 [[ 3.02018296  2.66923012]
 [ 2.73076397  2.2460237 ]]


### Question 2

In [ ]:
# Write a function which does the average convolution.
# Code for a 3d Matrix
# Before writing out code, write function header with parameters and get it reviewed by Mentors

# Lets Load an image and visualize the Conv and Pool

### Load the Conv and Max pool using Keras

In [ ]:
from keras.layers import Convolution2D, MaxPooling2D, Activation
from keras.models import Sequential


import numpy as np
import matplotlib.pyplot as plt
import cv2  # only used for loading the image, you can use anything that returns the image as a np.ndarray

%matplotlib inline

### Display the image

In [ ]:
image = cv2.imread('cat.png') # Please load different Images to explore 

In [ ]:
plt.imshow(image)

In [ ]:
# what does the image look like?
image.shape

## Level 3 - Performing and Understading Convolutions 

### Question 1 

### Why it has 3 dimensions ?? 

Answer - rgb

## Play Around with below code to enhance your understanding of CNN

## Lets create a model with 1 Convolutional layer

### Question 2

### Please fill in the comments 

In [ ]:
model = Sequential()
model.add(Convolution2D(3,    # number of filters
                        (3,    # row dimension of kernel 
                        3),    # column dimension of kernel
                        input_shape=image.shape))

In [ ]:
image_batch = np.expand_dims(image,axis=0)

### Question 3

### What Happens if we dont expand the dims of image ? Why we need to do it ?


Answer - error. because it requires number of images also.

In [ ]:
image_batch.shape

In [ ]:
conv_image = model.predict(image_batch)

In [ ]:
plt.imshow(np.squeeze(conv_image, axis=0))

In [ ]:
def visualize_image(model, image):

    image_batch = np.expand_dims(image,axis=0)
    conv_image = model.predict(image_batch)
    
    # here we get rid of that added dimension and plot the image
    conv_image = np.squeeze(conv_image, axis=0)
    
    print (conv_image.shape)
    plt.imshow(conv_image)

In [ ]:
visualize_image(model, image)

## Level 4 - Use Your Conv Function to visualize the image

### Question 1 - Call your function to perform conv and plot the image obatined 

## 10x10 Kernel Convimage

In [ ]:
model = Sequential()
model.add(Convolution2D(3,    
                        (10,    
                        10),    
                        input_shape=image.shape))


visualize_image(model, image)

## Level 5

### Question 1

### What difference you notice between 3\*3 and 10\*10 kernal size ? 

Answer - 

### Question 2

### What is the reason behing this difference ?

Answer -

# Play around with code below, to enhance your understading

## Another image Vis 

In [ ]:
# Note: matplot lib is pretty inconsistent with how it plots these weird image arrays.

def nice_image_printer(model, image):
    '''prints the image as a 2d array'''
    image_batch = np.expand_dims(image,axis=0)
    conv_image2 = model.predict(image_batch)

    conv_image2 = np.squeeze(conv_image2, axis=0)
    print (conv_image2.shape)
    conv_image2 = conv_image2.reshape(conv_image2.shape[:2])

    print (conv_image2.shape)
    plt.imshow(conv_image2)

In [ ]:
model = Sequential()
model.add(Convolution2D(1,    
                        (3,    
                        3),    
                        input_shape=image.shape))

In [ ]:
nice_image_printer(model, image)

### Question 3

### Why this image is different from previous one ?

Answer

## Increase the kernal size

In [ ]:
# 15x15 kernel size
model = Sequential()
model.add(Convolution2D(1,    
                        (15,    
                        15),   
                        input_shape=image.shape))

nice_image_printer(model, image)

## Adding a Relu Activation

In [ ]:
model = Sequential()
model.add(Convolution2D(1,    
                        (3,    
                        3),    
                        input_shape=image.shape))
# Lets add a new activation layer!
model.add(Activation('relu'))



In [ ]:
nice_image_printer(model, image)

## Adding a Max pool After Relu

In [ ]:
model = Sequential()
model.add(Convolution2D(3,    
                        (3,    
                        3),    
                        input_shape=image.shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(5,5)))

visualize_image(model, image)